[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[start]
cmd = "DATABASE_URL='file:./dev.db' npx prisma db push && DATABASE_URL='file:./dev.db' npm run start"
